language: java
dist: trusty
jdk:
- openjdk8
- oraclejdk8
after_success:
- mvn clean test jacoco:report coveralls:report
env:
  secure: "mWzxU4KxZyEcHWxU56odTq1CyA4mYVJkHBJsqjkqRIgPa9pTl9oYlsZ7XM1g8W909aZG0olP0/lzp8dw/bo6xE0/eI06mMAkDalEICPOTCZ8VZYV1I+SV1iHyYnB05QUKYoTnzLk7tjo39D9xGnGpVZB9r6ARZalpPz7OwBdus4="
sudo: false